# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date_time',
            field=models.DateTimeField(verbose_name=b'End'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date_time',
            field=models.DateTimeField(verbose_name=b'Start'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
