# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_calendar', '0003_auto_20170623_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolresult',
            name='balls_left',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=b'Loser Balls Left'),
        ),
    ]
