# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_calendar', '0005_speedrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedrun',
            name='verified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='speed_run_verifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
