# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170622_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=40, unique=True, verbose_name='user name'),
        ),
    ]
